TebLocalPlannerROS:
  ##=========================================================================================================================================================================================================
  ## ----- Robot Configuration Parameters -----
  acc_lim_x: 2.5 #
  acc_lim_theta: 5.0 #
  max_vel_x: 2.5 #
  max_vel_x_backwards: 0.2 #
  max_vel_theta: 5.0 #
  min_turning_radius: 0.0
  ##wheelbase: 1.0
  cmd_angle_instead_rotvel: false
  acc_lim_y: 1.0 #
  max_vel_y: 1.5 #
  ## ***** The following parameters are relevant for the footprint model used for optimization (see Tutorial Obstacle Avoidance and Robot Footprint Model). New in version 0.3 *****
  footprint_model/type: "polygon"
  footprint_model/radius: 0.18
  footprint_model/line_start: [-0.1, 0.0]
  footprint_model/line_end: [0.1, 0.0]
  footprint_model/front_offset: 0.2
  footprint_model/front_radius: 0.2
  footprint_model/rear_offset: 0.2
  footprint_model/rear_radius: 0.2
  footprint_model/vertices:
    [[0.17, 0.13], [0.17, -0.13], [-0.17, -0.13], [-0.17, 0.13]]
  is_footprint_dynamic: false
  ##=========================================================================================================================================================================================================
  ## ----- Goal Tolerance Parameters -----
  xy_goal_tolerance: 0.22
  yaw_goal_tolerance: 0.1
  free_goal_vel: false
  ##========================================================================================================================================================================================================
  ## ----- Trajectory Configuration Parameters -----
  dt_ref: 0.20 #
  dt_hysteresis: 0.04 #
  min_samples: 5
  global_plan_overwrite_orientation: true
  global_plan_viapoint_sep: 0.4 #
  max_global_plan_lookahead_dist: 1.0 #
  force_reinit_new_goal_dist: 0.3
  feasibility_check_no_poses: 4 #
  publish_feedback: false
  shrink_horizon_backup: true 
  allow_init_with_backwards_motion: false
  exact_arc_length: false
  shrink_horizon_min_duration: 10.0
  ##=========================================================================================================================================================================================================
  ## ----- Obstacle Parameters -----
  min_obstacle_dist: 0.039 #
  include_costmap_obstacles: true
  costmap_obstacles_behind_robot_dist: 0.3
  obstacle_poses_affected: 30
  inflation_dist: 0.0
  #include_dynamic_obstacles: true
  legacy_obstacle_association: false
  obstacle_association_force_inclusion_factor: 1.5
  obstacle_association_cutoff_factor: 5.0
  costmap_converter_plugin:
    "costmap_converter::CostmapToLinesDBSRANSAC"
    #costmap_converter_plugin: " "
  costmap_converter_spin_thread: true
  costmap_converter_rate: 5.0
  ##=========================================================================================================================================================================================================
  ## ----- Optimization Parameters -----
  no_inner_iterations: 5
  no_outer_iterations: 4
  penalty_epsilon: 0.1
  ##
  weight_max_vel_x: 1 #
  weight_max_vel_y: 1
  weight_max_vel_theta: 3.0
  weight_acc_lim_x: 1
  weight_acc_lim_y: 1
  weight_acc_lim_theta: 3
  weight_kinematics_nh: 1
  weight_kinematics_forward_drive: 1.0 #
  weight_kinematics_turning_radius: 0.0
  weight_optimaltime: 2.0 #time
  weight_obstacle: 50 #
  #weight_dynamic_obstacle: 10
  weight_viapoint: 10
  weight_inflation: 0.1
  weight_adapt_factor: 2.0
  ##=========================================================================================================================================================================================================
  ## ----- Parallel Planning in distinctive Topologies -----
  ##simple_exploration: False
  enable_homotopy_class_planning: true
  enable_multithreading: true
  max_number_classes: 4
  selection_cost_hysteresis: 1.0
  selection_obst_cost_scale: 100.0
  selection_viapoint_cost_scale: 1.0
  selection_alternative_time_cost: false
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 6
  h_signature_prescaler: 1.0
  h_signature_threshold: 0.1
  obstacle_heading_threshold: 1.0
  obstacle_keypoint_offset: 0.1
  visualize_hc_graph: false
  viapoints_all_candidates: true
  switching_blocking_period: 0.0
  ##=========================================================================================================================================================================================================
  ## ----- Miscellaneous Parameters -----
  odom_topic: "odom"
  map_frame: "map"
